import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};
 
export default sidebars;

// sidebar.js

// async function sidebarItemsGenerator({ defaultSidebarItemsGenerator, ...args }) {
//     const sidebarItems = await defaultSidebarItemsGenerator(args);
//     return skipIndex(sidebarItems);
//   }
  
//   function skipIndex(items) {
//     return items.filter(({ type, id }) => {
//       return type !== 'doc' || id !== 'index';
//     });
//   }
  
//   module.exports = sidebarItemsGenerator;
  